# Generated by Django 4.0.3 on 2026-01-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='admin_app.color'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_of_product', to='admin_app.product'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='product_varient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_of_product_varient', to='admin_app.productvarient'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_of_product', to='admin_app.product'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product_varient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_of_product_varient', to='admin_app.productvarient'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='admin_app.size'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_of_product', to='admin_app.product'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='product_varient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_of_product_varient', to='admin_app.productvarient'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_unit', to='admin_app.unit'),
        ),
    ]
