# Generated by Django 4.0.3 on 2026-01-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
