# Generated by Django 4.2.11 on 2026-01-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_alter_categories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='moq',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
