# Generated by Django 4.2.11 on 2026-01-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_product_is_popular_product_moq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='moq',
        ),
    ]
