# Generated by Django 4.2.11 on 2026-01-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_remove_product_moq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moq',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
