# Generated by Django 4.2.11 on 2026-01-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_product_moq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarient',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
