# Generated by Django 4.2.11 on 2026-01-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_alter_productvarient_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsubcategories',
            name='categories',
        ),
    ]
