# Generated by Django 4.2.11 on 2026-01-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_remove_subsubcategories_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
