# Generated by Django 4.2.11 on 2026-01-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='campaign_name',
        ),
        migrations.AddField(
            model_name='slider',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_order_item_slider', to='admin_app.product'),
            preserve_default=False,
        ),
    ]
