# Generated by Django 4.2.11 on 2026-01-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_shippingaddress_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
