# Generated by Django 4.2.11 on 2026-01-18 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_orderitem_sub_total'),
        ('admin_app', '0017_remove_slider_campaign_name_slider_product'),
    ]

    operations = [
    ]
