# Generated by Django 4.2.11 on 2026-01-19 04:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_merge_20260118_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('is_percentage', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flash_sell_product', to='admin_app.product')),
            ],
        ),
    ]
