# Generated by Django 4.2.11 on 2026-01-19 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_flashsell'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsell',
            name='side_slider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flash_sell_side_slider', to='admin_app.sideslider'),
        ),
        migrations.AddField(
            model_name='flashsell',
            name='slider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flash_sell_slider', to='admin_app.slider'),
        ),
        migrations.AlterField(
            model_name='flashsell',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sell_product', to='admin_app.product'),
        ),
    ]
