# Generated by Django 4.2.11 on 2026-01-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_flashsell_side_slider_flashsell_slider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsell',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flashsell',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
