# Generated by Django 4.2.11 on 2026-01-20 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_merge_20260117_1644'),
        ('admin_app', '0022_alter_flashsell_product_alter_flashsell_side_slider_and_more'),
    ]

    operations = [
    ]
