# Generated by Django 4.2.11 on 2026-01-20 04:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_alter_flashsell_product_alter_flashsell_side_slider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_charge_unit', to='admin_app.unit')),
            ],
        ),
    ]
