# Generated by Django 4.2.11 on 2026-01-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_deliverycharge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliverycharge',
            unique_together={('unit', 'amount')},
        ),
    ]
