# Generated by Django 4.2.11 on 2026-01-20 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0024_alter_deliverycharge_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_color', to='admin_app.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_attribute', to='admin_app.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product_varient',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='product_varient',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='productvarient',
            name='stock_qty',
        ),
        migrations.AddField(
            model_name='productvarient',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_varient_unit', to='admin_app.unit'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='ProductUnit',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product_varient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_varient_attribute', to='admin_app.productvarient'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_size', to='admin_app.size'),
        ),
    ]
