# Generated by Django 4.2.11 on 2026-01-20 10:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0025_productattribute_remove_productimage_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvarient',
            old_name='buying_price',
            new_name='sold_count',
        ),
        migrations.RemoveField(
            model_name='productvarient',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='productvarient',
            name='height',
        ),
        migrations.RemoveField(
            model_name='productvarient',
            name='regular_price',
        ),
        migrations.RemoveField(
            model_name='productvarient',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='productvarient',
            name='width',
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productattribute',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productattribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
