# Generated by Django 4.2.11 on 2026-01-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_rename_buying_price_productvarient_sold_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
