# Generated by Django 4.2.11 on 2026-01-23 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_productattribute_is_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_product_attribute', to='admin_app.productattribute'),
            preserve_default=False,
        ),
    ]
