# Generated by Django 4.2.11 on 2026-01-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0028_remove_cartitem_product_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute_order_item', to='admin_app.productattribute'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_varient_item', to='admin_app.productvarient'),
        ),
    ]
