# Generated by Django 4.2.11 on 2026-01-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_merge_20260120_0325'),
        ('admin_app', '0029_orderitem_product_attribute_and_more'),
    ]

    operations = [
    ]
