# Generated by Django 4.2.11 on 2026-01-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0030_order_shipping_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
