# Generated by Django 4.2.11 on 2026-01-23 17:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0031_order_shipping_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_delivery', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('discount_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('min_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('type', models.CharField(choices=[('', '--SELECT--'), ('delivery', 'Delivery'), ('product', 'Product')], default='delivery', max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='deliverycharge',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='increment_weight_per_unit',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='initial_charge',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='initial_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initial_unit_of_product', to='admin_app.unit'),
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='initial_weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='sub_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_charge_sub_sub_category', to='admin_app.subsubcategories'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='deliverycharge',
            name='amount',
        ),
    ]
