# Generated by Django 4.2.11 on 2026-01-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0030_merge_20260123_1355'),
        ('admin_app', '0031_order_shipping_method'),
    ]

    operations = [
    ]
