# Generated by Django 4.2.11 on 2026-01-23 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0032_deliverydiscount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_delivery_discount', to='admin_app.deliverydiscount'),
            preserve_default=False,
        ),
    ]
