# Generated by Django 4.2.11 on 2026-01-24 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0032_merge_20260123_1513'),
        ('admin_app', '0033_product_delivery_discount'),
    ]

    operations = [
    ]
