# Generated by Django 4.2.11 on 2026-01-24 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0034_merge_20260124_0314'),
        ('admin_app', '0034_recentlyviewedproduct'),
    ]

    operations = [
    ]
