# Generated by Django 4.2.11 on 2026-01-24 06:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0034_recentlyviewedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=30)),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('type', models.CharField(choices=[('', '--SELECT--'), ('delivery', 'Delivery'), ('product', 'Product')], max_length=20)),
                ('min_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('number_of_user', models.PositiveIntegerField()),
                ('is_percent', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
