# Generated by Django 4.2.11 on 2026-01-24 07:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0035_couponmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_tax_amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
    ]
