# Generated by Django 4.2.11 on 2026-01-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0036_product_is_applicable_product_vat_tax_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverycharge',
            name='sub_sub_category',
        ),
        migrations.CreateModel(
            name='SubSubCategoryDeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_charge_of_sub_sub_category', to='admin_app.deliverycharge')),
                ('sub_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_charge_sub_sub_category', to='admin_app.subsubcategories')),
            ],
        ),
    ]
