# Generated by Django 4.2.11 on 2026-01-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0035_merge_20260124_0432'),
        ('admin_app', '0036_product_is_applicable_product_vat_tax_amount'),
    ]

    operations = [
    ]
