# Generated by Django 4.2.11 on 2026-01-24 11:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0037_remove_deliverycharge_sub_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycharge',
            name='delivery_location',
            field=models.CharField(choices=[('', '--SELECT--'), ('inside_dhaka', 'Inside Dhaka'), ('outside_dhaka', 'Outside Dhaka')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='gst_amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
    ]
