# Generated by Django 4.2.11 on 2026-01-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0038_deliverycharge_delivery_location_product_gst_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydiscount',
            name='flat_delivery',
            field=models.FloatField(default=-1),
        ),
    ]
