# Generated by Django 4.2.11 on 2026-01-25 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0039_alter_deliverydiscount_flat_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_of_order', to='admin_app.couponmanagement'),
        ),
    ]
