# Generated by Django 4.2.11 on 2026-01-26 03:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0040_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gst_amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_tax_amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
