# Generated by Django 4.2.11 on 2026-01-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0037_merge_20260124_0817'),
        ('admin_app', '0040_order_coupon'),
    ]

    operations = [
    ]
