# Generated by Django 4.2.11 on 2026-01-26 03:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0041_alter_product_gst_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarient',
            name='sold_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
