# Generated by Django 4.2.11 on 2026-01-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0043_alter_productattribute_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_color', to='admin_app.color'),
        ),
    ]
