# Generated by Django 4.2.11 on 2026-01-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0044_alter_productattribute_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmanagement',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
