# Generated by Django 4.2.11 on 2026-01-26 13:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0045_alter_couponmanagement_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmanagement',
            name='min_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
