# Generated by Django 4.2.11 on 2026-01-27 03:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0046_alter_couponmanagement_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydiscount',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='deliverydiscount',
            name='min_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
