# Generated by Django 4.2.11 on 2026-01-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0041_merge_0037_merge_20260124_0817_0040_order_coupon'),
        ('admin_app', '0046_alter_couponmanagement_min_price'),
    ]

    operations = [
    ]
