# Generated by Django 4.2.11 on 2026-01-27 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0047_alter_deliverydiscount_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_delivery_discount', to='admin_app.deliverydiscount'),
        ),
    ]
