# Generated by Django 4.2.11 on 2026-01-27 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0048_alter_product_delivery_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsell',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flash_sell_product', to='admin_app.product'),
        ),
    ]
