# Generated by Django 4.2.11 on 2026-01-27 09:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0049_alter_flashsell_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydiscount',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
