# Generated by Django 4.2.11 on 2026-01-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0050_alter_deliverydiscount_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlyviewedproduct',
            name='view_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
