# Generated by Django 4.2.11 on 2026-01-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0047_merge_20260127_0322'),
        ('admin_app', '0051_recentlyviewedproduct_view_count'),
    ]

    operations = [
    ]
