# Generated by Django 4.2.11 on 2026-01-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0052_merge_20260128_0355'),
        ('admin_app', '0052_merge_20260128_1648'),
    ]

    operations = [
    ]
