# Generated by Django 4.2.11 on 2026-01-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0052_merge_20260128_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_campaign', to='admin_app.sideslider'),
        ),
    ]
