# Generated by Django 4.2.11 on 2026-01-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0053_product_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
