# Generated by Django 4.2.11 on 2026-01-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0054_cartitem_color_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycharge',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
