# Generated by Django 4.2.11 on 2026-01-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0053_merge_20260129_0840'),
        ('admin_app', '0054_cartitem_color_cartitem_size'),
    ]

    operations = [
    ]
