# Generated by Django 4.2.11 on 2026-01-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0056_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
