# Generated by Django 4.2.11 on 2026-01-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0055_merge_20260129_1033'),
        ('admin_app', '0057_cart_delivery_location'),
    ]

    operations = [
    ]
