# Generated by Django 4.2.11 on 2026-01-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0058_merge_20260130_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approval',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('not_approved', 'Not Approved')], default='not_approved', max_length=150, null=True),
        ),
    ]
