# Generated by Django 4.2.11 on 2026-02-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0059_product_approval'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product_attribute')},
        ),
    ]
