# Generated by Django 4.2.11 on 2026-02-01 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0060_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='product_varient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_varient_attribute', to='admin_app.productvarient'),
        ),
    ]
