# Generated by Django 4.2.11 on 2026-02-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0061_alter_productattribute_product_varient'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_flash_sale',
            field=models.BooleanField(default=False),
        ),
    ]
