# Generated by Django 4.2.11 on 2026-02-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0063_product_is_flash_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_flash_sale',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='is_flash_sale',
        ),
    ]
