# Generated by Django 4.2.11 on 2026-02-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0064_remove_product_is_flash_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo_height',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='logo_width',
            field=models.IntegerField(default=10),
        ),
    ]
