# Generated by Django 4.2.11 on 2026-02-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0064_remove_product_is_flash_sale_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='slider',
        #     name='Product',
        # ),
        migrations.AddField(
            model_name='slider',
            name='name',
            field=models.CharField(max_length=100, unique=True,null=True),
            preserve_default=False,
        ),
    ]
