# Generated by Django 4.2.11 on 2026-02-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0065_remove_slider_product_slider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideslider',
            name='campaign_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
