# Generated by Django 4.2.11 on 2026-02-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0065_sitesetting_logo_height_sitesetting_logo_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='logo_height',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='logo_width',
        ),
    ]
