# Generated by Django 4.2.11 on 2026-02-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0065_rename_discount_amount_order_coupon_price_and_more'),
        ('admin_app', '0066_remove_sitesetting_logo_height_and_more'),
        ('admin_app', '0067_product_is_active'),
    ]

    operations = [
    ]
