# Generated by Django 4.2.11 on 2026-02-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0068_merge_20260202_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='approval',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('not_approved', 'Not Approved')], default='approved', max_length=150, null=True),
        ),
    ]
