# Generated by Django 4.2.11 on 2026-02-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0069_alter_product_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('', '--SELECT--'), ('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
