# Generated by Django 4.2.11 on 2026-02-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0069_alter_product_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideslider',
            name='campaign_type',
            field=models.CharField(choices=[('campaign', 'Campaign'), ('flash_sale', 'Flash Sale')], default='flash_sale', max_length=150),
        ),
    ]
