# Generated by Django 4.2.11 on 2026-02-03 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0070_sideslider_campaign_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsell',
            name='side_slider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='flash_sell_side_slider', to='admin_app.sideslider'),
            preserve_default=False,
        ),
    ]
