# Generated by Django 4.2.11 on 2026-02-03 08:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0070_order_payment_method_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmanagement',
            name='min_price',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
