# Generated by Django 4.2.11 on 2026-02-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0071_alter_flashsell_side_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashsell',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='flashsell',
            name='start_date',
        ),
    ]
