# Generated by Django 4.2.11 on 2026-02-03 08:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0072_alter_cart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmanagement',
            name='min_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
