# Generated by Django 4.2.11 on 2026-02-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0072_remove_flashsell_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideslider',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sideslider',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
