# Generated by Django 4.2.11 on 2026-02-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0073_alter_couponmanagement_min_price'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='campaign',
        # ),
        migrations.RemoveField(
            model_name='productvarient',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('', '--SELECT--'), ('pending', 'Pending'), ('confirm', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
