# Generated by Django 4.2.11 on 2026-02-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0073_sideslider_end_date_sideslider_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideslider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
