# Generated by Django 4.2.11 on 2026-02-03 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0074_alter_sideslider_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarient',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_varient', to='admin_app.product'),
        ),
    ]
