# Generated by Django 4.2.11 on 2026-02-03 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0075_alter_productvarient_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_product_attribute',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_ui_representator', to='admin_app.productattribute'),
        ),
    ]
