# Generated by Django 4.2.11 on 2026-02-03 08:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0076_product_cover_product_attribute'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sideslider',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='sideslider',
            name='is_active',
        ),
    ]
