# Generated by Django 4.2.11 on 2026-02-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0077_alter_sideslider_managers_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='campaign',
        # ),
    ]
