# Generated by Django 4.2.11 on 2026-02-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0078_remove_product_campaign'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flashsell',
            unique_together={('product', 'side_slider')},
        ),
    ]
