# Generated by Django 4.2.11 on 2026-02-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0074_remove_product_campaign_remove_productvarient_status_and_more'),
        ('admin_app', '0079_alter_flashsell_unique_together'),
    ]

    operations = [
    ]
