# Generated by Django 4.2.11 on 2026-02-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0081_remove_product_campaign_remove_slider_product_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='campaign',
        # ),
        # migrations.RemoveField(
        #     model_name='slider',
        #     name='Product',
        # ),
    ]
