# Generated by Django 4.2.11 on 2026-02-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0081_alter_order_order_status'),
        ('admin_app', '0082_remove_product_campaign_remove_slider_product'),
    ]

    operations = [
    ]
