# Generated by Django 4.2.11 on 2026-02-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0083_merge_20260204_1824'),
        ('admin_app', '0083_merge_20260204_1902'),
    ]

    operations = [
    ]
