# Generated by Django 4.2.11 on 2026-02-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0084_merge_20260205_1606'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='campaign',
        # ),
        # migrations.RemoveField(
        #     model_name='slider',
        #     name='Product',
        # ),
        migrations.AlterField(
            model_name='productattribute',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='admin_app.color'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute', to='admin_app.product'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product_varient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_varient_attribute', to='admin_app.productvarient'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='admin_app.size'),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='admin_app.brand'),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_varient_unit', to='admin_app.unit'),
        ),
    ]
