# Generated by Django 4.2.11 on 2026-02-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0083_merge_20260204_1859'),
        ('admin_app', '0085_remove_product_campaign_remove_slider_product_and_more'),
    ]

    operations = [
    ]
