# Generated by Django 4.2.11 on 2026-02-07 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0085_remove_product_campaign_remove_slider_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycharge',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_charge_unit', to='admin_app.unit'),
        ),
    ]
