# Generated by Django 4.2.11 on 2026-02-08 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0086_merge_20260207_1007'),
        ('admin_app', '0087_order_delivery_date'),
    ]

    operations = [
    ]
