# Generated by Django 4.2.11 on 2026-02-08 07:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0088_merge_20260208_1036'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='campaign',
        # ),
        # migrations.RemoveField(
        #     model_name='slider',
        #     name='Product',
        # ),
        migrations.AlterField(
            model_name='deliverydiscount',
            name='min_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterUniqueTogether(
            name='deliverycharge',
            unique_together={('delivery_location', 'is_active')},
        ),
    ]
