# Generated by Django 4.2.11 on 2026-02-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0088_merge_20260208_1019'),
        ('admin_app', '0089_remove_product_campaign_remove_slider_product_and_more'),
    ]

    operations = [
    ]
