# Generated by Django 4.2.11 on 2026-02-09 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0090_merge_20260208_2102'),
    ]

    operations = [
#         migrations.RemoveField(
#             model_name='product',
#             name='campaign',
#         ),
#         migrations.RemoveField(
#             model_name='slider',
#             name='Product',
#         ),
        # migrations.AddField(
        #     model_name='privacypolicy',
        #     name='is_active',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='termscondition',
        #     name='is_active',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='campaign',
        # ),
        # migrations.RemoveField(
        #     model_name='slider',
        #     name='Product',
        # ),
        migrations.AddField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d+$', 'Only numeric digits (start with optional +) are allowed.')]),
        ),
    ]
