# Generated by Django 4.2.11 on 2026-02-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0091_remove_product_campaign_remove_slider_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
