# Generated by Django 4.2.11 on 2026-02-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0091_remove_product_campaign_remove_slider_product_2_and_more'),
        ('admin_app', '0093_sitesetting_company_apple_app_and_more'),
    ]

    operations = [
    ]
