# Generated by Django 4.2.11 on 2026-02-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0094_merge_20260209_1907'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='campaign',
        # ),
        # migrations.RemoveField(
        #     model_name='slider',
        #     name='Product',
        # ),
    ]
