# Generated by Django 4.2.11 on 2026-02-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0095_remove_product_campaign_remove_slider_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='Product',
        ),
    ]
