# Generated by Django 4.2.11 on 2026-02-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0097_themesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
