# Generated by Django 4.2.11 on 2026-02-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0098_sitesetting_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydiscount',
            name='type',
            field=models.CharField(default='delivery', max_length=20),
        ),
    ]
