# Generated by Django 4.2.11 on 2026-02-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0099_alter_deliverydiscount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydiscount',
            name='type',
            field=models.CharField(blank=True, default='delivery', max_length=20),
        ),
    ]
