# Generated by Django 4.2.11 on 2026-02-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0100_alter_deliverydiscount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsubcategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
