# Generated by Django 4.2.11 on 2026-02-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0101_subsubcategories_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_color', models.CharField(default='#761731', max_length=20)),
                ('notification_color', models.CharField(default='#EF4444', max_length=20)),
                ('price_color', models.CharField(default='#EF4444', max_length=20)),
                ('button_color', models.CharField(default='#EB2E61', max_length=20)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
