# Generated by Django 4.2.11 on 2026-02-24 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0102_clientthemesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_of_employee', to='admin_app.categories')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_of_category', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
