# Generated by Django 4.2.11 on 2026-02-24 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0103_employeecategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_of_employee', to='admin_app.categories'),
        ),
        migrations.AlterField(
            model_name='employeecategories',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_of_category', to=settings.AUTH_USER_MODEL),
        ),
    ]
