# Generated by Django 4.2.11 on 2026-02-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0104_alter_employeecategories_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
