# Generated by Django 4.2.11 on 2026-03-04 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0105_orderitem_buying_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_attribute_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute_image', to='admin_app.productattribute')),
            ],
        ),
    ]
