# Generated by Django 4.2.11 on 2026-03-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0106_productattributeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='termscondition',
            name='head',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('terms_and_conditions', 'Terms & Conditions'), ('privacy_and_policy', 'Privacy Policy'), ('return_refund', 'Return & Refund Policy'), ('warranty', 'Warranty Policy'), ('emi', 'EMI Policy')], max_length=100, null=True),
        ),
    ]
