# Generated by Django 4.2.11 on 2026-03-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0107_termscondition_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_categories/'),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_sub_categories/'),
        ),
    ]
