# Generated by Django 4.2.11 on 2026-03-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0108_subcategories_image_alter_subsubcategories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tiktok',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='xhandle',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
