# Generated by Django 4.2.11 on 2026-03-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0109_sitesetting_instagram_sitesetting_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='american_express',
            field=models.ImageField(blank=True, null=True, upload_to='site/payement-method/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bkash',
            field=models.ImageField(blank=True, null=True, upload_to='site/payement-method/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cash',
            field=models.ImageField(blank=True, null=True, upload_to='site/payement-method/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='dbbl',
            field=models.ImageField(blank=True, null=True, upload_to='site/payement-method/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='easy_monthly',
            field=models.ImageField(blank=True, null=True, upload_to='site/payement-method/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mastercard',
            field=models.ImageField(blank=True, null=True, upload_to='site/payement-method/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nagad',
            field=models.ImageField(blank=True, null=True, upload_to='site/payement-method/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='rocket',
            field=models.ImageField(blank=True, null=True, upload_to='site/payement-method/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='visa',
            field=models.ImageField(blank=True, null=True, upload_to='site/payement-method/'),
        ),
    ]
