# Generated by Django 4.2.11 on 2026-03-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0110_sitesetting_american_express_sitesetting_bkash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentMethodLogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='payment_method_logos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='american_express',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='bkash',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='dbbl',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='easy_monthly',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='mastercard',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='nagad',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='rocket',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='visa',
        ),
    ]
