# Generated by Django 4.2.11 on 2026-04-02 07:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0111_paymentmethodlogos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
    ]
