# Generated by Django 4.2.11 on 2026-04-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0112_productattribute_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
