# Generated by Django 4.2.11 on 2026-04-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0113_slider_slider_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteadfastConsignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_address', models.TextField(blank=True, null=True)),
                ('cod_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('hold', 'Hold'), ('delivered_approval_pending', 'Delivered Approval Pending'), ('partial_delivered_approval_pending', 'Partial Delivered Approval Pending'), ('cancelled_approval_pending', 'Cancelled Approval Pending'), ('unknown_approval_pending', 'Unknown Approval Pending'), ('delivered', 'Delivered'), ('partial_delivered', 'Partial Delivered'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], default='pending', max_length=100)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consignment', to='admin_app.order')),
            ],
        ),
    ]
