# Generated by Django 4.2.11 on 2026-04-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0115_courier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathaoCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=250)),
                ('secret_key', models.CharField(max_length=250)),
                ('base_url', models.URLField(max_length=500)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('store_id', models.IntegerField(blank=True, null=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('zone_id', models.IntegerField(blank=True, null=True)),
                ('area_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedxCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=250)),
                ('pickup_store_id', models.CharField(blank=True, max_length=100)),
                ('pickup_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
