# Generated by Django 4.2.11 on 2026-04-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0116_pathaocourier_redxcourier'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='provider',
            field=models.CharField(blank=True, default='steadfast', max_length=20),
        ),
        migrations.AddField(
            model_name='pathaocourier',
            name='provider',
            field=models.CharField(blank=True, default='pathao', max_length=20),
        ),
        migrations.AddField(
            model_name='redxcourier',
            name='provider',
            field=models.CharField(blank=True, default='redx', max_length=20),
        ),
    ]
