# Generated by Django 4.2.11 on 2026-04-15 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0117_courier_provider_pathaocourier_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathaoConsignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_address', models.TextField(blank=True, null=True)),
                ('recipient_city', models.IntegerField(blank=True, null=True)),
                ('recipient_zone', models.IntegerField(blank=True, null=True)),
                ('cod_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_type', models.IntegerField(blank=True, null=True)),
                ('item_type', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pickup_requested', 'Pickup Requested'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('hold', 'Hold')], default='pending', max_length=100)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pathao_consignment', to='admin_app.order')),
            ],
        ),
    ]
