# Generated by Django 4.2.11 on 2026-04-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0118_pathaoconsignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='redxcourier',
            name='is_sandbox',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RedxConsignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('delivery_area', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_area_id', models.IntegerField(blank=True, null=True)),
                ('cash_collection_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parcel_weight', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('hold', 'Hold')], default='pending', max_length=100)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redx_consignment', to='admin_app.order')),
            ],
        ),
    ]
