# Generated by Django 4.2.11 on 2026-04-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0119_redxcourier_is_sandbox_redxconsignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='redxcourier',
            name='base_url',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
