# Generated by Django 4.2.11 on 2026-04-22 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0120_redxcourier_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_sub_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_sub_sub_categories', to='admin_app.subsubcategories'),
        ),
    ]
