# Generated by Django 4.2.11 on 2026-05-11 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0121_alter_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
