# Generated by Django 4.2.11 on 2026-04-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0121_alter_product_sub_sub_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='column',
            field=models.CharField(choices=[('', '--SELECT'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategories',
            name='has_sub_sub_cat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='position',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
