# Generated by Django 4.2.11 on 2026-04-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0122_subcategories_column_subcategories_has_sub_sub_cat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategories',
            options={'ordering': ['column', 'position']},
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='column',
            field=models.CharField(choices=[('', '--SELECT--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10),
        ),
    ]
