# Generated by Django 4.2.11 on 2026-05-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0122_order_edited_at_order_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_stock_violated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='violated_qty',
            field=models.IntegerField(default=0),
        ),
    ]
