# Generated by Django 4.2.11 on 2026-04-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0123_alter_subcategories_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='whatsapp',
        ),
    ]
