# Generated by Django 4.2.11 on 2026-04-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0124_remove_sitesetting_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='messenger',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
