# Generated by Django 4.2.11 on 2026-04-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0125_sitesetting_messenger_sitesetting_whatsapp_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategories',
            unique_together={('column', 'position')},
        ),
    ]
