# Generated by Django 4.2.11 on 2026-04-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0126_alter_subcategories_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategories',
            unique_together={('sub_cat_name', 'column', 'position')},
        ),
    ]
