# Generated by Django 4.2.11 on 2026-05-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0121_alter_shippingaddress_city_and_more'),
        ('admin_app', '0128_alter_subcategories_unique_together'),
    ]

    operations = [
    ]
