# Generated by Django 4.2.11 on 2026-09-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0130_order_edited_at_order_edited_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='column',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
