# Generated by Django 4.2.11 on 2026-01-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Admin'), ('sectionadmin', 'SectionAdmin'), ('employee', 'Employee'), ('customer', 'Customer')], max_length=20),
        ),
    ]
