# Generated by Django 4.2.11 on 2026-01-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Admin'), ('sectionadmin', 'SectionAdmin'), ('employee', 'Employee'), ('customer', 'Customer')], max_length=20, null=True),
        ),
    ]
