# Generated by Django 4.2.11 on 2026-01-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_user_gender_user_name_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('sectionadmin', 'Section Admin'), ('employee', 'Employee')], max_length=20, null=True),
        ),
    ]
