# Generated by Django 4.2.11 on 2026-01-31 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0058_merge_20260130_1031'),
        ('accounts_app', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to='admin_app.categories'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('cerntral_admin', 'Central Admin'), ('sectionadmin', 'Section Admin'), ('employee', 'Employee')], max_length=20, null=True),
        ),
    ]
