# Generated by Django 4.2.11 on 2026-01-31 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_user_category_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
