# Generated by Django 4.2.11 on 2026-02-01 08:27

import accounts_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0008_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts_app.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('central_admin', 'Central Admin'), ('sectionadmin', 'Section Admin'), ('employee', 'Employee')], max_length=20, null=True),
        ),
    ]
