# Generated by Django 4.2.11 on 2026-02-01 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0009_alter_user_managers_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numeric digits are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('customer', 'Customer'), ('central_admin', 'Central Admin'), ('sectionadmin', 'Section Admin'), ('employee', 'Employee')], max_length=20, null=True),
        ),
    ]
