# Generated by Django 4.2.11 on 2026-02-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0011_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('customer', 'Customer'), ('central_admin', 'Central Admin'), ('section_admin', 'Section Admin'), ('employee', 'Employee')], max_length=20, null=True),
        ),
    ]
