# Generated by Django 4.2.11 on 2026-02-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0103_employeecategories'),
        ('accounts_app', '0014_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='user_category', to='admin_app.categories'),
        ),
    ]
