# Generated by Django 4.2.11 on 2026-02-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0015_remove_user_category_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('central_admin', 'Central Admin'), ('section_admin', 'Category Admin'), ('employee', 'Employee')], max_length=20, null=True),
        ),
    ]
