# Generated by Django 4.2.11 on 2026-08-27 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_brachname_contact_no'),
        ('accounts_app', '0016_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pos_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_user_branch', to='pos_app.brachname'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('ecommerce', 'E-commerce'), ('pos', 'POS'), ('both', 'Both')], max_length=100, null=True),
        ),
    ]
