# Generated by Django 4.2.11 on 2026-08-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0017_user_pos_branch_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pos_role',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('central_admin', 'Central Admin'), ('branch_admin', 'Branch Admin'), ('regular_user', 'Regular User')], max_length=100, null=True),
        ),
    ]
