# Generated by Django 4.2.11 on 2026-08-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0018_user_pos_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
