# Generated by Django 4.2.11 on 2026-08-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brachname',
            name='contact_no',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
