# Generated by Django 4.2.11 on 2026-08-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_brachname_contact_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brachname',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='brachname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='brachname',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
