# Generated by Django 4.2.11 on 2026-08-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brachname',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
