# Generated by Django 4.2.11 on 2026-08-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0006_brachname_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='due_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
