# Generated by Django 4.2.11 on 2026-09-12 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0131_alter_subcategories_column_and_more'),
        ('pos_app', '0007_supplier_due_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_product_attribute', to='admin_app.productattribute')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_product_branch', to='pos_app.brachname')),
            ],
        ),
    ]
