# Generated by Django 4.2.11 on 2026-09-14 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0131_alter_subcategories_column_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos_app', '0008_posproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_qty', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('', '--SELECT--'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_pull_requests', to='admin_app.productattribute')),
                ('request_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pull_requests_made', to=settings.AUTH_USER_MODEL)),
                ('requesting_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pull_requests_created', to='pos_app.brachname')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pull_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pull_requests_received', to='pos_app.brachname')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('qty', models.PositiveIntegerField()),
                ('source_stock_after', models.IntegerField(blank=True, null=True)),
                ('dest_stock_after', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_logs', to='admin_app.productattribute')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pos_app.stockpullrequest')),
                ('requesting_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs_as_requester', to='pos_app.brachname')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs_as_source', to='pos_app.brachname')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
