# Generated by Django 4.2.11 on 2026-09-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0009_stockpullrequest_stocktransferlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransferlog',
            name='event',
            field=models.CharField(choices=[('', '--SELECT--'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10),
        ),
    ]
