# Generated by Django 4.2.11 on 2026-03-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
