# Generated by Django 4.2.11 on 2026-03-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_reviewrating_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
