# Generated by Django 4.2.11 on 2026-02-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpanelpermissions',
            name='permission',
            field=models.CharField(choices=[('', '--SELECT--'), ('product_approval_permission', 'Product Approval Permission'), ('order_management_permission', 'Order Management Permission')], max_length=150),
        ),
    ]
