# Generated by Django 4.2.11 on 2026-02-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_app', '0003_alter_adminpanelpermissions_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpanelpermissions',
            name='permission',
            field=models.CharField(choices=[('', '--SELECT--'), ('product_approval_permission', 'Product Approval Permission'), ('order_management_permission', 'Order Management Permission'), ('campaign_management_permission', 'Campaign Management Permission'), ('slider_management_permission', 'Slider  Image Manage Permission'), ('employee_management_permission', 'Employee Management Permission'), ('permission_management', 'Permission Management'), ('category_management', 'Category Manage Permission'), ('product_management', 'Product Management Permission'), ('product_variant_management', 'Product Variant Management Permission'), ('promotion_management', 'Promotion Management Permission'), ('delivery_management', 'Delivery Management Permission'), ('coupon_management', 'Coupon Management Permission'), ('company_info_permission', 'Company Info Manage Permission'), ('term_and_condition_permission', 'Term and Condition Manage Permission'), ('privacy_policy_permission', 'Privacy Policy Manage Permission'), ('update_just_for_you_permission', 'Update Just For You Manage Permission'), ('theme_change_permission', 'Theme Change Permission')], max_length=150),
        ),
    ]
