# Generated by Django 4.2.11 on 2026-08-29 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permission_app', '0005_alter_adminpanelpermissions_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosPanelPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('', '--SELECT--'), ('pos_billing', 'POS (Billing)'), ('due_collection', 'Due Collection'), ('refund', 'Refund'), ('order_update', 'Order Update'), ('supplier', 'Supplier'), ('purchase_order', 'Purchase Order'), ('purchase_history', 'Purchase History'), ('grn', 'GRN (Goods Received Note)'), ('product_reconciliation', 'Product Reconciliation'), ('stock_transfer', 'Stock Transfer'), ('expense_head', 'Expense Head'), ('expense_entry', 'Expense Entry'), ('cash_bank_ledger', 'Cash / Bank Ledger'), ('supplier_due_payment', 'Supplier Due / Payment'), ('product_master', 'Product Master'), ('customer_master', 'Customer Master'), ('branch_counter_setup', 'Branch / Counter Setup'), ('report_profit_loss', 'Profit & Loss'), ('report_sale_summary', 'Sale Summary'), ('report_sale_details', 'Sale Details'), ('report_due_summary', 'Due Summary'), ('report_due_details', 'Due Details'), ('report_income_statement', 'Income Statement'), ('report_refund_collection', 'Refund & Collection'), ('report_expense', 'Expense Report'), ('report_stock_inventory', 'Stock / Inventory')], max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_panel_permission_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
